#! /usr/bin/env bash

export BUILD_MODE=${BUILD_MODE:-testing}

network=`docker network ls | grep havokmud | tr -s " " | cut -d " " -f 2`
if [ -z "${network}" ] ; then
    docker network create havokmud
fi

if [ "${BUILD_MODE}" = "testing" ] ; then
    #conda init bash
    #conda activate HavokMud-redux
    container=`docker ps --format '{{.Names}}' | grep localstack-main`
    if [ "${container}" != "localstack-main" ]; then
	screen -d -m -S localstack
        screen -S localstack -X screen -t localstack
        screen -S localstack -p localstack -X exec localstack start
	
	echo "Waiting for localstack docker image to start"

	while true; do
            container=`docker ps --format '{{.Names}}' | grep localstack_main`
            if [ "${container}" = "localstack_main" ]; then
                break
	    fi
            sleep 2
	done
        docker rename localstack_main localstack-main
        docker network connect havokmud localstack-main
    fi
fi

LOGDIR=`cd ../logs ; pwd`
chmod 1777 ${LOGDIR}

docker rm havokmud
screen -d -m -S havokmud
screen -S havokmud -X screen -t mud
screen -S havokmud -p m$ud -X exec docker run -p 3000:3000 --network havokmud --name havokmud -v ${LOGDIR}:/var/log/havokmud  -it havokmud:latest ./start-in-docker
screen -S havokmud -p mud -X exec docker attach havokmud
screen -r -S havokmud
